exclude: 'docs'
fail_fast: false
repos:
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
    language_version: python3.12
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    language_version: python3.12
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    language_version: python3.12
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
  - id: mypy
    language_version: python3.12
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
